#!/bin/bash
[ -z "$PS1" ] && return

LOCAL="$HOME/.bashrc_local"

rcfiles=$(ls -1 ~/.shrc.d/ | grep -e "\.sh$" -e "\.bash$")
for rcfile in $rcfiles; do
	. ~/.shrc.d/$rcfile
done

touch $LOCAL
. $LOCAL

if ! [ -z "$AUTOCD" ]; then
        cd "$AUTOCD"
fi

which starship 2>&1 > /dev/null && eval "$(starship init bash)"
