#! /bin/sh -x

# Hotkeys
sxhkd &

# Auto update xrandr config
autorandr -c

# Workspaces
monitors=($(xrandr --listactivemonitors | awk '{print $4}' | sed '/^$/d'))
if [ "${#monitors[@]}" == "2" ]; then
        bspc monitor ${monitors[1]} -d 1
        bspc monitor ${monitors[0]} -d 2 3 4 5 6 7 8 9
else
        bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# Basic config
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config automatic_scheme alternate

# Manually manage ewmh features
bspc config ignore_ewmh_focus     true
bspc config ignore_ewmh_fullscreen true

# Only pad master monitor (for status bar)
bspc config top_padding 0
bspc config -m ${monitors[0]} top_padding 20

# Rules
bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled

# Set background
feh --bg-scale ~/.wmbg

# Default Cursor
xsetroot -cursor_name left_ptr

# Keyboard layout
setxkbmap gb

# Compositing
picom &

# Load xresources
xrdb ~/.Xresources

# Ensure pulseaudio is running
if ! ps -U $USER | grep pulseaudio; then
        pulseaudio &
fi

# desktop notifications
killall statnot
statnot ~/.config/statnot/rc.py &

# Status bar
killall bspstatus
bspstatus &

# Open pidgin conversation window if urgent flag is set
pidmon &
