if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

match ErrorMsg '\s\+$'

syntax on
filetype plugin indent on

":set expandtab"
":set tabstop=4"
