" Leader
:let mapleader = ","

" Vundle config
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'neovimhaskell/haskell-vim'
Plugin 'wagnerf42/vim-clippy'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-sleuth'
Plugin 'cespare/vim-toml'
Plugin 'tpope/vim-surround'
Plugin 'dense-analysis/ale'
call vundle#end()            " required
filetype plugin indent on    " required

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g'\"" | endif
endif

match ErrorMsg '\s\+$'

"Gui options
:set guioptions-=T
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar
:set guifont=Inconsolata\ 12

" Editor options
:set iskeyword-=_
"set mouse-=a"
:set expandtab
:set tabstop=4
filetype plugin indent on
syntax on
highlight Normal ctermfg=white ctermbg=NONE
:set so=5

" Relative number
:set number relativenumber
:set nu rnu
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

" Use bar on insert mode
autocmd VimEnter,InsertLeave * silent exec "! echo -ne '\e[1 q'"
autocmd VimLeave,InsertEnter * silent exec "! echo -ne '\e[5 q'"

"File types
autocmd Filetype gitcommit setlocal spell textwidth=72
au BufReadPost,BufNewFile .xmobarrc setlocal ft=haskell
