LOCALRC="$HOME/.zshrc_local"
SHRCD="$HOME/.shrc.d"

# Include all files from ~/.shrc.d
set -o shwordsplit
rcfiles=$(ls -1 $SHRCD | grep -e "\.sh$" -e "\.zsh$")
for rcfile in $rcfiles; do
        . ~/.shrc.d/$rcfile
done

touch $LOCALRC
. $LOCALRC

