#!/bin/sh
BOOKMARK_FILE=~/.config/bookmarks.txt

function options {
	xclip -o -selection clipboard | tr -d '\n'
	echo " # Clipboard"
	cat $BOOKMARK_FILE
}

if [ "$1" == "-n" ]; then
	shift
	site=$(xclip -o -selection clipboard)
	bookmark=$(dmenu -t -p "Bookmark: $site #")
	if [ -z "$bookmark" ]; then
		exit 0
	fi
	echo "$site # $bookmark" >> $BOOKMARK_FILE
elif [ "$1" == "-e" ];then
	$EDITOR $BOOKMARK_FILE
else
	bookmark=$(options | dmenu -p "Surf: " -i -l 10 | sed 's/[^\\]#.*$//;s/\\#/#/g')
	if ! [ -z "$bookmark" ]; then
		surf -P "$bookmark"
	fi
fi
