#!/bin/sh
BOOKMARK_FILE=~/.config/bookmarks.txt
if [ "$1" == "-n" ]; then
	shift
	site=$(xclip -o)
	bookmark=$(dmenu -t -p "Bookmark: $site #")
	if [ -z "$bookmark" ]; then
		exit 0
	fi
	echo "$site # $bookmark" >> $BOOKMARK_FILE
else
	bookmark=$(cat $BOOKMARK_FILE | dmenu -p "Surf: " -i -l 10 | sed 's/[^\\]#.*$//;s/\\#/#/g')
	if ! [ -z "$bookmark" ]; then
		surf -P "$bookmark"
	fi
fi
