#!/usr/bin/env python
import toml
import json
import sys

try:
    jsonData = sys.stdin.read()
except Exception as e:
    print("Failed to read input data: %s" % str(e), file = sys.stderr)
    exit(1)

try:
    dictData = json.loads(jsonData)
except Exception as e:
    print("Failed to parse json data: %s" % str(e), file = sys.stderr)
    exit(1)

try:
    tomlData = toml.dumps(dictData)
except Exception as e:
    print("Failed to generate toml: %s" % str(e), file = sys.stderr)
    exit(1)

print(tomlData)
