#!/bin/bash
device=$1; shift

function get_net_devices {

	ip link show | sed -n 's/[0-9]\+: \(.*\):.*$/\1/p'
}

function get_device_ip {
	device=$1; shift
	ip addr show $device | sed -n 's/.*inet \([0-9\.]\+\)\/.*/\1/p'
}

function show_devices {
	echo "Available devices:" >> /dev/stderr
	for d in $devices; do
		echo $d >> /dev/stderr
	done
}

devices=$(get_net_devices)

if ! [[ "$device" ]]; then
	echo "Usage: $(basename $0) device" >> /dev/stderr
	show_devices
	exit 1
fi

if ! echo $devices | grep $device > /dev/null; then
	echo "Device $device not found"
	show_devices
	exit 1
fi

ip=$(get_device_ip $device)

if ! [[ $ip ]]; then
	echo "$device seems to have no IPv4 address" >> /dev/stderr
	exit 1
fi

nmap_addr=$(echo $ip | sed 's/\./ /g' | awk '{print $1"."$2"."$3".*"}')

nmap -sP $nmap_addr
