#!/bin/bash
alias screen="screen -h 10240"
screens="$(screen -ls | tail -n+2 | head -n-1 | sort -t. -k2)"
title=Screen

if [[ $1 ]]; then
	screens="$(echo "$screens" | grep -e "^\s[0-9]\+\.$1" | tee /dev/stderr)"
	title="$title ($1)"

fi

count=$(expr $(echo "$screens" | wc -w) / 2 + 1)
height=0
width=0

if [[ $1 ]] && [ "$(echo "$screens" | wc -l)" == "1" ]; then
	selection=$(echo $screens | awk '{print $1}')
else
	selection=$(dialog --keep-tite --menu "$title" $height $width $count "New Screen" "..." $screens --stdout)
fi

if [ "$selection" == "New Screen" ]; then
	selection=$(dialog --keep-tite --inputbox "Name?" $height $width --stdout)
fi

if [[ ! "$selection" ]]; then
	exit 0
fi

if echo "$screens" | grep $selection | grep Attached > /dev/null; then
	dialog --keep-tite --yesno "Force Detach?" $height $width --stdout || { exit 0; }
fi
screen -Rd $selection
