#!/bin/sh
if [ -z $1 ]; then
        echo "Usage: $(basename $0) shell [grep pattern]" > /dev/stderr
        exit 1
fi
shell=$1; shift

if ! [ -z $1 ]; then
    match="grep $1"; shift
else
    match="cat"
fi

pushd ~ >/dev/null
files="$(echo .${shell}rc && find .shrc.d/ -name '*.sh' -o -name "*.$shell" | sort)"
files="$(echo "$files" | $match)"
popd >/dev/null

if ! [ $(echo "$files" | wc -l) == "1" ]; then
    selection=$(echo "$files" | fzf)
else
    selection=$files
fi

if ! [ -z $selection ]; then
    $EDITOR ~/$selection
else
    exit 1
fi
