#!/bin/bash
alias screen="screen -h 10240"
screens="$(screen -ls | sed -n '/ached/s/^\s\+//p' | sort -t. -k2)"
title=Screen
height=0
width=0

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: $(basename $0) [-h|--help] [-k] [pattern]"
	exit 0
fi

if [[ $1 == "-k" ]]; then
	# Multikill
	echo "$screens" | fzf -m | \
		while read screen extra; do
			echo "Killing screen session '$screen'" > /dev/stderr
			screen -S $screen -X quit
		done
	exit 0
fi

if [[ $1 ]]; then
	screens="$(echo "$screens" | grep -e "^\s*[0-9]\+\.$1")"
	title="$title ($1)"
fi

count=$(expr $(echo "$screens" | wc -w) / 2 + 1)

if [[ $1 ]] && [ "$(echo "$screens" | wc -l)" == "1" ]; then
	selection=$(echo "$screens" | awk '{print $1}')
else
	selection=$(echo -e "New Screen\n$screens" | fzf | awk '{print $1}')
fi

if [ "$selection" == "New" ]; then
	read -p "Name > " selection
fi

if [ -z "$selection" ]; then
	exit 0
fi

if echo "$screens" | grep $selection | grep Attached > /dev/null; then
	while true; do
		read -p "Force Detach [Y/n]" detach
		if [ "$detach" == "y" ] || [ -n "$detach" ]; then
			break
		elif [ "$detatch" == "n" ]; then
			exit 0
		fi
	done
fi

echo "Opening session '$selection'" >> /dev/stderr
screen -Rd $selection
