#!/bin/bash
fifo=/tmp/statusbar
font=$(sed -n 's/st.font: \(.*\)/\1/p' ~/.Xresources)
self=$0
mods="$HOME/.local/dzen2"
left_bar_ratio=0.45

# Unicode Chars
right_triangle="\ue0b0"
left_triangle="\ue0b2"

# Colors
cbg1="#444455"

# -k option to kill statusbar
if [ "$1" == "-k" ]; then
	echo "kill 0" >> $fifo
	exit 0
fi

# Formatting functions
function cbg {
	color=$1; shift
	echo -n "^bg($color)$@^bg()"
}

function cfg {
	color=$1; shift
	echo -n "^fg($color)$@^fg()"
}

function shorten {
	len=$1; shift
	var="$@"
	if [ "${#var}" -gt "$len" ]; then
		echo -n "${var:0:$len}\u2026"
	else
		echo -n "$var"
	fi
}

# Add a space to non-empty strings
function pad {
	if grep -q "[^ ]" <<< "$@"; then
		echo "$@ "
	else
		echo
	fi
}

# Get Screen Width
screen_width=$(xrandr --listactivemonitors | sed -n '2s/.* \([0-9]\+\)\/.*/\1/p')
left_bar_width=$(bc <<< "( $screen_width * $left_bar_ratio )" | sed 's/\..*//')
echo "screen width = $screen_width"
echo "left bar = $left_bar_width"

# dzen commands
function dzen_left {
	sleep 0.2s
	dzen2 -xs 1 -ta l -dock -fn "$font" -tw $left_bar_width -bg "#000000"
}

function dzen_right {
	dzen2 -xs 1 -ta r -dock -fn "$font" -bg "#000000"
}

# Cleanup on exit
function cleanup {
	trap - SIGINT SIGTERM
	kill -- -$$
}
trap cleanup SIGINT SIGTERM

# Periodically run a command and pipe to statusbar
# Usage: period <name> <period> <command>
function period {
	name=$1; shift
	slp=$1; shift
	cmd=$@
	while true; do
		$cmd 2> /dev/null
		sleep $slp
	done | while read output; do
		echo $name "$output" >> $fifo
	done
}

# Start modules
function sbdate {
	datev=$(date "+%a %b %_d")
	timev=$(date "+%k:%M")
	echo -e "$datev $(cfg "#000000" $(cbg $cbg1 $right_triangle))$(cbg $cbg1 $timev)"
}
period date			10s	sbdate &
period battery		1m 	"$mods/battery.sh" &
period bitcoin		1m 	"$mods/bitcoin.sh" &
period bluetooth	10s "$mods/bluetooth.sh" &
period kbmap		10s "$mods/kbmap.sh" &
period mail			1m	"$mods/mail.sh" &
period mem			5s	"$mods/mem.sh" &
period network		5s	"$mods/network.sh" &
period song			5s	"$mods/song.sh" &
period volume		1s	"$mods/volume.sh" &
period weather		1m	"$mods/weather.sh" &

# Working Varaibles
ws=""
layout=""
title=""
datev=""
battery=""
bitcoin=""
bluetooth=""
kbmap=""
mail=""
mem=""
network=""
song=""
volume=""
weather=""

# Parse information from fifo and pass to dzen2
tail -f -n1 $fifo | while read cmd line; do
	case $cmd in
		ws) ws="$(cbg $cbg1 " $line ")$(cfg $cbg1 "$right_triangle")"
			;;
		layout) layout="$(cfg "#22ff22" "$line")"
			;;
		title) title="$line"
			;;
		date) datev="$(cfg "#88ff88" $line)"
			;;
		battery) battery="$line"
			;;
		bitcoin) bitcoin="$line"
			;;
		bluetooth) bluetooth="$line"
			;;
		kbmap) kbmap="$line"
			;;
		mail) mail="$(pad $line)"
			;;
		mem) mem="$line"
			;;
		network) network="$line"
			;;
		song) song=$(pad $(shorten 30 $line))
			;;
		volume) volume="$line"
			;;
		weather) weather="$line"
			;;
		kill) echo "Got kill command, exiting..." 1>&2
			break
			;;
	esac

	# Left Bar
	echo -e "$ws $layout $(cfg "#000000" $(cbg $cbg1 $right_triangle))$(cbg $cbg1 ' '$title' ')$(cfg $cbg1 $right_triangle)" 1>&5

	# Right Bar
	echo -e "$bitcoin $mail$song$bluetooth$network $kbmap $volume $mem $battery $weather $datev" 1>&6
done 6> >(dzen_right) 5> >(dzen_left)

kill -- -$$
