#!/usr/bin/env python
import toml
import json
import sys

try:
    tomlData = sys.stdin.read()
except Exception as e:
    print("Failed to read input data: %s" % str(e), file = sys.stderr)
    exit(1)

try:
    dictData = toml.loads(tomlData)
except Exception as e:
    print("Failed to parse toml data: %s" % str(e), file = sys.stderr)
    exit(1)

try:
    jsonData = json.dumps(dictData)
except Exception as e:
    print("Failed to generate json: %s" % str(e), file = sys.stderr)
    exit(1)

print(jsonData)
