#!/bin/sh
lists="
https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt
https://easylist.to/easylist/fanboy-annoyance.txt
https://easylist.to/easylist/fanboy-social.txt
https://raw.githubusercontent.com/liamja/Prebake/master/obtrusive.txt
https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt
https://crapblock.theel0ja.info/even-cleaner-news-sites.txt
https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
https://raw.githubusercontent.com/ilyakatz/adblock_filters/master/inpage_popups.txt
https://raw.githubusercontent.com/Rudloff/adblock-imokwithcookies/master/filters.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt
$HOME/.config/wyebadblock/custom.txt
"
output=$HOME/.config/wyebadblock/easylist.txt

rm $output

echo "Updating $output..."
for list in $lists; do
	if [ -z "$list" ]; then
		continue
	fi
	if [ -f "$list" ]; then
		echo "CAT $list"
		cat $list >> $output
	else
		echo "CURL $list"
		curl $list >> $output
	fi
done
